version: '3'
services:
  
  backend:
    build:
      context: backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    
  interface:
    build: 
      context: interface
    ports:
      - "8080:8080"
    depends_on:
      - backend
    